### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by mbodock** [pagarme/pagarme-python#18]
Would be nice have some guidelines for new contributors to follow.

**Comment by chrisenytc** [comment]
It's a great idea. I am working on it. I am creating a contributing guide for our open-source projects.

**Comment by rodrigoPgSup** [comment]
Hey @mbodock about the contribution. We're adding @victormessina to the repo, so he can help us improve the code. See ya

And @chrisenytc , You're most!

**Comment by mbodock** [comment]
hello @rodrigoPgSup any particular reason to add @VictorMessina to the repo?

As i stated before, it's not a good approach push directly to the main repository, even if it is in another branch.

Also I'd like to politely ask you to remove your branch https://github.com/pagarme/pagarme-python/tree/include-partial-capture, and continue your work in a fork.

**Comment by derekstavis** [comment]
Hi @mbodock, thanks for your concerns. I'd like to give some responses about them.

>hello @rodrigoPgSup any particular reason to add @VictorMessina to the repo?

Yes. He is working on our support team and is willing to help with development.

>As i stated before, it's not a good approach push directly to the main repository, even if it is in another branch.
>Also I'd like to politely ask you to remove your branch https://github.com/pagarme/pagarme-python/tree/include-partial-capture, and continue your work in a fork.

Indeed this is about our missing contribution guide!

I have recently took ownership in dealing with Pagar.me open source repositories, willing to standardize them, so I should give a treatment to README, badges, and contribution guides in next weeks.

About _this_ specific point, most of our team agree that contributors can push into the main repository, as it makes easier to fetch and push new commits -- you know, sometimes a pull request branch is just missing a character or have a little bug that you want to address yourself instead of asking your coworker to do it. The only condition of pushing to main repository is that we need to get the branches deleted when pull requests are merged, and also when they are refused.

Again, thanks for your thoughts and feel free to add feedback :+1:

**Comment by MarcoWorms** [comment]
Like Derek just said, here at Pagar.me we don't have the habbit of forking to make branches in a fork, IMO this shouldn't be a problem since you can just delete branches after the PR is closed or refused. If you have a good motive for us to do that, please elaborate the point to change our minds. As of now we don't see a reason to follow a rule like this :)

**Comment by mbodock** [comment]
@MarcoWorms Well it's an approach, I personally don't like. I'd rather review and squash the PR outside the main repository. It is slower, but more safe, specially with this, a payment related repository.

Another huge thing I'd like to state is, this repository is in the pagar.me's namespace because you guys asked for, but it is kept mainly by me. An external maintainer, which also possess the ownership rights.

I see no problem with you guys overwhelming my will, but from now on, I'm will no longer worker here.

I just ask to please respect the code's license and my copyrights.

Good luck for you guys

**Comment by MarcoWorms** [comment]
@mbodock well, if you want to stop contributing that's totally up to you, but we are not overwhelming your will. Like I said, you can change our minds if you give us a reason to not do this. That's part of Pagarme's culture and we are always open to change our opinion on any subject when good reasons are given :+1:

**Comment by felquis** [comment]
#20

**Comment by murilohns** [comment]
Hey guys, i'm closing this issue, but if you need, just open it again :smile:
